//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Trinity.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.1.0.0")]
    public sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));

        //public static Settings Default
        //{
        //    get
        //    {
        //        return defaultInstance;
        //    }
        //}

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("20030515")]
        public uint MagicMainNet {
            get {
                return ((uint)(this["MagicMainNet"]));
            }
            set {
                this["MagicMainNet"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("19990331")]
        public uint MagicTestNet {
            get {
                return ((uint)(this["MagicTestNet"]));
            }
            set {
                this["MagicTestNet"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("7630401")]
        public uint NeoMagicMainNet {
            get {
                return ((uint)(this["NeoMagicMainNet"]));
            }
            set {
                this["NeoMagicMainNet"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1953787457")]
        public uint NeoMagicTestNet {
            get {
                return ((uint)(this["NeoMagicTestNet"]));
            }
            set {
                this["NeoMagicTestNet"] = value;
            }
        }
    }
}
