//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Trinity.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.0.0.0")]
    public sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        /*
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        */
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("20030515")]
        public uint MagicMainNet {
            get {
                return ((uint)(this["MagicMainNet"]));
            }
            set {
                this["MagicMainNet"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("19990331")]
        public uint MagicTestNet {
            get {
                return ((uint)(this["MagicTestNet"]));
            }
            set {
                this["MagicTestNet"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("7630401")]
        public uint NeoMagicMainNet {
            get {
                return ((uint)(this["NeoMagicMainNet"]));
            }
            set {
                this["NeoMagicMainNet"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1953787457")]
        public uint NeoMagicTestNet {
            get {
                return ((uint)(this["NeoMagicTestNet"]));
            }
            set {
                this["NeoMagicTestNet"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0xc56f33fc6ecfcd0c225c4ab356fee59390af8560be0e930faebe74a6daff7c9b")]
        public string NeoAssetId {
            get {
                return ((string)(this["NeoAssetId"]));
            }
            set {
                this["NeoAssetId"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0x602c79718b16e442de58778e148d0b1084e3b2dffd5de6b7b16cee7969282de7")]
        public string NeoGasAssetId {
            get {
                return ((string)(this["NeoGasAssetId"]));
            }
            set {
                this["NeoGasAssetId"] = value;
            }
        }
    }
}
